version: "3"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=cart
      - POSTGRES_PASSWORD=secret
      - POSTGERES_DB=cart
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONFIG_FILE="test.toml"
    ports:
      - 8080:8080
      - 8090:8090
